// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brsxhknhakodidfrifzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyc3hoa25oYWtvZGlkZnJpZnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NjMyMDYsImV4cCI6MjA3MjUzOTIwNn0.Uc7k4epV3eYWatTyny4mD9Er82CxpUZg8tZ7mrJ4_tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});