// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnojwdyxrtbzwhjtgvfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRub2p3ZHl4cnRiendoanRndmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzUxMjgsImV4cCI6MjA3MjQ1MTEyOH0.q9ez4IZ2H9m1Jk9w8hULs-ko7amw7eYthuIc--rJhJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});